### ISSUE TITLE
无法以只读模式打开数据库文件。 确保数据库存在，以便使用只读模式。

### ISSUE THREAD

**Issue by Justus-wang** [bboysoulcn/awesome-dockercompose#3]
以前配的没有问题这次配置就一直这样，能麻烦给说一下吗？
系统是Centos 7.7
内核是3.10.0-1062.1.1.el7.x86_64(用过5.3.0也不行)
Docker version 19.03.2, build 6a30dfc
docker-compose version 1.24.1, build 4667896b

报错日志：
         Client generating RPC Bind Request...
Server receiving
<===============        Client sending RPC Bind Request...
Server sending
===============>        Client received RPC Bind Response !!!
       RPC Bind acknowledged !!!
       Client generating Activation Request dictionary...
       Client generating Activation Request data...
       Client generating RPC Activation Request...
Server receiving
<===============        Client sending RPC Activation Request...
Server sending
===============>        Client received Response !!!

Traceback (most recent call last):
  File "pykms_Client.py", line 268, in <module>
    clt_main(with_gui = False)
  File "pykms_Client.py", line 190, in clt_main
    client_create()
  File "pykms_Client.py", line 151, in client_create
    parsed = MSRPCRespHeader(response)
  File "/home/py-kms/pykms_Dcerpc.py", line 641, in __init__
    MSRPCHeader.__init__(self, aBuffer, alignment)
  File "/home/py-kms/pykms_Dcerpc.py", line 588, in __init__
    Structure.__init__(self,data, alignment)
  File "/home/py-kms/pykms_Structure.py", line 110, in __init__
    self.fromString(data)
  File "/home/py-kms/pykms_Structure.py", line 167, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataCl                                                                                                                                                      assOrCode, field = field[0])
  File "/home/py-kms/pykms_Structure.py", line 329, in unpack
    return self.unpack(two[0],data)
  File "/home/py-kms/pykms_Structure.py", line 385, in unpack
    return unpack(format, b(data))[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver                                                                                                                                                      _major | B=5 | ''[:1]'")
Unable to open database file in read-only mode. Ensure that the database exists                                                                                                                                                       in order to use read-only mode.

**Comment by bboysoulcn** [comment]
> 以前配的没有问题这次配置就一直这样，能麻烦给说一下吗？
> 系统是Centos 7.7
> 内核是3.10.0-1062.1.1.el7.x86_64(用过5.3.0也不行)
> Docker version 19.03.2, build 6a30dfc
> docker-compose version 1.24.1, build 4667896b
> 
> 报错日志：
> Client generating RPC Bind Request...
> Server receiving
> <=============== Client sending RPC Bind Request...
> Server sending
> ===============> Client received RPC Bind Response !!!
> RPC Bind acknowledged !!!
> Client generating Activation Request dictionary...
> Client generating Activation Request data...
> Client generating RPC Activation Request...
> Server receiving
> <=============== Client sending RPC Activation Request...
> Server sending
> ===============> Client received Response !!!
> 
> Traceback (most recent call last):
> File "pykms_Client.py", line 268, in
> clt_main(with_gui = False)
> File "pykms_Client.py", line 190, in clt_main
> client_create()
> File "pykms_Client.py", line 151, in client_create
> parsed = MSRPCRespHeader(response)
> File "/home/py-kms/pykms_Dcerpc.py", line 641, in **init**
> MSRPCHeader.**init**(self, aBuffer, alignment)
> File "/home/py-kms/pykms_Dcerpc.py", line 588, in **init**
> Structure.**init**(self,data, alignment)
> File "/home/py-kms/pykms_Structure.py", line 110, in **init**
> self.fromString(data)
> File "/home/py-kms/pykms_Structure.py", line 167, in fromString
> self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataCl assOrCode, field = field[0])
> File "/home/py-kms/pykms_Structure.py", line 329, in unpack
> return self.unpack(two[0],data)
> File "/home/py-kms/pykms_Structure.py", line 385, in unpack
> return unpack(format, b(data))[0]
> struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'ver _major | B=5 | ''[:1]'")
> Unable to open database file in read-only mode. Ensure that the database exists in order to use read-only mode.

不懂
