### ISSUE TITLE
volumes迁移的问题

### ISSUE THREAD

**Issue by zhangqijun** [bboysoulcn/awesome-dockercompose#4]
我尝试了直接迁移 /var/lib/docker/volumes文件夹到新的机器，但是存在很多目录权限的问题导致容器启动失败。还有网上备份volumes方法为每个容器内的路径压缩为一个tar，但是逐个打包恢复过于麻烦。请问备份恢复有什么方式可以推荐吗？

**Comment by bboysoulcn** [comment]
> 我尝试了直接迁移 /var/lib/docker/volumes文件夹到新的机器，但是存在很多目录权限的问题导致容器启动失败。还有网上备份volumes方法为每个容器内的路径压缩为一个tar，但是逐个打包恢复过于麻烦。请问备份恢复有什么方式可以推荐吗？


保持权限不变可以使用rsync

rsync -pgoav --progress root@10.10.10.10:/var/lib/docker/volumes /var/lib/docker/volumes
